version: 2

updates:

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 10

    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"


  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 10

    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
